version = 5.6.0
archive_dir = /Users/nicogomez/Github/mgseguridad/ssl-letsencrypt-rsa/letsencrypt/config/archive/koscap.com.ar
cert = /Users/nicogomez/Github/mgseguridad/ssl-letsencrypt-rsa/letsencrypt/config/live/koscap.com.ar/cert.pem
privkey = /Users/nicogomez/Github/mgseguridad/ssl-letsencrypt-rsa/letsencrypt/config/live/koscap.com.ar/privkey.pem
chain = /Users/nicogomez/Github/mgseguridad/ssl-letsencrypt-rsa/letsencrypt/config/live/koscap.com.ar/chain.pem
fullchain = /Users/nicogomez/Github/mgseguridad/ssl-letsencrypt-rsa/letsencrypt/config/live/koscap.com.ar/fullchain.pem
[renewalparams]
account = 77a59c5370a99926496f6b41c6262df9
rsa_key_size = 2048
key_type = rsa
pref_challs = http-01,
config_dir = /Users/nicogomez/Github/mgseguridad/ssl-letsencrypt-rsa/letsencrypt/config
work_dir = /Users/nicogomez/Github/mgseguridad/ssl-letsencrypt-rsa/letsencrypt/work
logs_dir = /Users/nicogomez/Github/mgseguridad/ssl-letsencrypt-rsa/letsencrypt/logs
authenticator = manual
manual_auth_hook = /Users/nicogomez/Github/mgseguridad/ssl-letsencrypt-rsa/ftp-auth-hook.sh
manual_cleanup_hook = /Users/nicogomez/Github/mgseguridad/ssl-letsencrypt-rsa/ftp-cleanup-hook.sh
server = https://acme-v02.api.letsencrypt.org/directory
